### ISSUE TITLE
Build Failing after #919

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#920]
@SolarLune 
Rebased my master branch from current master (latest PR: #919). But when building I'm getting this Error message:
```java
...
build:
    [mkdir] Created dir: D:\BDX\GitHub\bdx\build
    [javac] Compiling 45 source files to D:\BDX\GitHub\bdx\build
    [javac] D:\BDX\GitHub\bdx\src\com\nilunder\bdx\Bdx.java:340: error: local variable scene is accessed from within inner class; needs to be declared final
    [javac]                                             program.setUniformf("near", scene.camera.near());
    [javac]                                                                         ^
    [javac] D:\BDX\GitHub\bdx\src\com\nilunder\bdx\Bdx.java:341: error: local variable scene is accessed from within inner class; needs to be declared final
    [javac]                                             program.setUniformf("far", scene.camera.far());
    [javac]                                                                        ^
    [javac] 2 errors

BUILD FAILED
D:\BDX\GitHub\bdx\build.xml:82: Compile failed; see the compiler error output for details.
...
```

**Comment by SolarLune** [comment]
Huh, strange. 

Guessing it's something that's more lax on JRE8 than on JRE7.

**Comment by rafcolson** [comment]
>Guessing it's something that's more lax on JRE8 than on JRE7.

Yes. It seems so.

PR merged. Thank you.
